# Generated by Django 4.2.11 on 2026-06-08 00:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arete', models.CharField(max_length=50)),
                ('especie', models.CharField(choices=[('alpaca', 'Alpaca'), ('llama', 'Llama'), ('ovino', 'Ovino')], max_length=10)),
                ('sexo', models.CharField(choices=[('hembra', 'Hembra'), ('macho', 'Macho')], max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
                ('raza', models.CharField(blank=True, default='', max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animales/')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('sync_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('sincronizado', 'Sincronizado'), ('error', 'Error')], default='sincronizado', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_maternos', to='animales.animal')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_paternos', to='animales.animal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'db_table': 'animales',
                'ordering': ['-created_at'],
            },
        ),
    ]
