# Generated by Django 4.2.11 on 2026-06-17 22:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_esquila', models.DateField()),
                ('peso_vellon_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rendimiento_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('sync_status', models.CharField(choices=[('pendiente', 'Pendiente'), ('sincronizado', 'Sincronizado'), ('error', 'Error')], default='sincronizado', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='animales.animal')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'db_table': 'producciones',
                'ordering': ['-fecha_esquila'],
                'indexes': [models.Index(fields=['animal', 'fecha_esquila'], name='idx_producciones_animal_fecha')],
            },
        ),
    ]
