# Generated by Django 4.2.30 on 2026-06-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0004_v2_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produccion',
            options={'ordering': ['animal', 'numero_esquila'], 'verbose_name': 'Producción', 'verbose_name_plural': 'Producciones'},
        ),
        migrations.AlterField(
            model_name='animal',
            name='estado',
            field=models.CharField(choices=[('VIVO', 'Vivo'), ('VENDIDO', 'Vendido'), ('MUERTO', 'Muerto')], default='VIVO', max_length=10),
        ),
    ]
