# Generated by Django 4.2.30 on 2026-06-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0006_alter_produccion_numero_esquila'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='produccion',
            constraint=models.UniqueConstraint(fields=('animal', 'numero_esquila'), name='uq_animal_numero_esquila'),
        ),
    ]
