# Generated by Django 4.2.30 on 2026-06-26 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animales', '0007_validaciones_produccion_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_empadre', models.DateField()),
                ('fecha_dx_gestacion', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente'), ('positivo', 'Positivo'), ('negativo', 'Negativo'), ('no_revisado', 'No revisado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empadres_hembra', to='animales.animal')),
                ('macho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empadres_macho', to='animales.animal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empadres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empadre',
                'verbose_name_plural': 'Empadres',
                'db_table': 'empadres',
                'ordering': ['-fecha_empadre'],
            },
        ),
        migrations.AddField(
            model_name='produccion',
            name='diametro_fibra_micras',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Diámetro de fibra (micras)'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='factor_confort',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Factor de confort (%)'),
        ),
        migrations.AddField(
            model_name='produccion',
            name='medulacion_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Medulación (%)'),
        ),
        migrations.CreateModel(
            name='VentaFibra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kg_vendidos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('precio_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprador', models.CharField(blank=True, default='', max_length=200)),
                ('fecha_venta', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_fibra', to='animales.animal')),
                ('produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='animales.produccion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_fibra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta de fibra',
                'verbose_name_plural': 'Ventas de fibra',
                'db_table': 'ventas_fibra',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_parto', models.DateField()),
                ('fecha_probable', models.DateField(blank=True, null=True)),
                ('numero_crias', models.PositiveSmallIntegerField(default=1)),
                ('incidencias', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partos', to='animales.empadre')),
                ('hembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='animales.animal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'db_table': 'partos',
                'ordering': ['-fecha_parto'],
            },
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(choices=[('alimentacion', 'Alimentación'), ('sanidad', 'Sanidad'), ('esquila', 'Esquila'), ('transporte', 'Transporte'), ('otro', 'Otro')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='animales.animal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Costo',
                'verbose_name_plural': 'Costos',
                'db_table': 'costos',
                'ordering': ['-fecha'],
            },
        ),
    ]
