# Generated by Django 4.2.30 on 2026-07-01 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(default='999888777', max_length=15)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='pagos/')),
                ('monto_basico', models.DecimalField(decimal_places=2, default=7.9, max_digits=10)),
                ('monto_criador', models.DecimalField(decimal_places=2, default=19.9, max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración de Pago',
                'verbose_name_plural': 'Configuración de Pago',
                'db_table': 'configuracion_pago',
            },
        ),
        migrations.CreateModel(
            name='SolicitudPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_solicitado', models.CharField(choices=[('gratuito', 'Gratuito'), ('basico', 'Básico'), ('criador', 'Criador')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.ImageField(upload_to='comprobantes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_pago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solicitudes_pago',
                'ordering': ['-created_at'],
            },
        ),
    ]
